- docs/logging-best-practices.rst
- docs/standard-library.rst
This PR adds examples to the 'best practices' docs to get structlog to play nice with logstash and logstash-forwarder
> Improve suggested stdlib configuration (e.g. for structlog+logstash+forwarder)

- docs/configuration.rst
- structlog/stdlib.py
> Nano-tweaks

- AUTHORS.rst
- docs/configuration.rst
> Simple spelling correciton; exaplained to explained

- setup.py
- src/structlog/stdlib.py
This might come in handy so that new PRs don't fail by default 🙃
> Flake8 fixes

- docs/processors.rst
Feel free to request changes or even decline. I just thought it'd be easier to ask the question 'can/should this be added to the docs' in the form of a PR.
> Add note about third party processors to docs

- CHANGELOG.rst
- src/structlog/stdlib.py
- tests/test_stdlib.py
> Fix add_logger_name processor not working in foreign_prechain.

- docs/standard-library.rst
This adds a (I think) gentler introduction to the way that ProcessorFormatter
works. The existing dictConfig remains. I wasn't sure if I should maybe add
another couple of headings to the docs to make it more clear, we're already at
the maximum nesting level in sphinx so it won't show up in the ToC anyway.
I think that if this had existed I wouldn't have opened #138
> Add docs around using ProcessorFormatter

- docs/logging-best-practices.rst
> Fix typo in logging-best-practices.

- src/structlog/_config.py
- src/structlog/_generic.py
- src/structlog/_loggers.py
This made the comment hard to understand.
> Fix typo in docstrings

- docs/performance.rst
I've been using it for a few months now in a side project, where it beat out rapidjson & ujson in my basic benchmarks
> Recommend another JSON library

- docs/getting-started.rst
> Fix a typo in Getting started

- CHANGELOG.rst
- docs/api.rst
- docs/thread-local.rst
- src/structlog/threadlocal.py
- tests/test_threadlocal.py
> Add get_threadlocal & get_merged_threadlocal

- CHANGELOG.rst
- docs/api.rst
- src/structlog/contextvars.py
- tests/test_contextvars.py
- tests/test_threadlocal.py
> Add get_contextvars & get_merged_contextvars

- CHANGELOG.rst
- docs/processors.rst
- src/structlog/_base.py
- src/structlog/types.py
- tests/test_base.py
> Support bytearrays as last return value

- .github/PULL_REQUEST_TEMPLATE.md
Link to explanation of "Allow edits from maintainers".
I did not know this option existed and the way
I was managing forks was hiding it from me.
This change adds a link to a page explaining the option
to let people know it exists in case they are doing the same thing I was.
This is just a friendly reminder about the most common mistakes.
Please make sure that you tick all boxes.
But please read our [contribution guide](https://github.com/hynek/structlog/blob/main/.github/CONTRIBUTING.md) at least once; it will save you unnecessary review cycles!
Find the appropriate next version in our …
> Link to explanation of "Allow edits from maintainers"

- CHANGELOG.md
- docs/api.rst
- docs/contextvars.rst
- docs/index.rst
- docs/thread-local.rst
- pyproject.toml
- src/structlog/threadlocal.py
- tests/test_contextvars.py
- tests/test_processors.py
- tests/test_threadlocal.py
- tox.ini
> Deprecate structlog.threadlocal

- docs/why.rst
Hi 👋 
I'm actually not sure if this is a typo. Is it? If it's not, sorry. 👀
> Fix typo on `why.rst`

- src/structlog/_log_levels.py
- tests/test_log_levels.py
Ensures that contextvars are copied in the same context as the caller of the async logging method, and then references that context inside callable that is run in the executor thread.
Closes #462
> Async log methods: copy contextvars outside of executor.

- src/structlog/dev.py
> docs: fix spelling

- docs/conf.py
- docs/standard-library.md
looks it's impossible to change the theme with Mermaid 10 without introducing the JavaScript build hell @mgaitan? :(
ref #497
> Fix Mermaid diagrams for Mermaid 10

- docs/contextvars.md
Would this be adequate @Jdsleppy & @dabljues?
ref #491
> contextvars: add warning about hybrid apps

- CHANGELOG.md
- src/structlog/_frames.py
- src/structlog/dev.py
- tests/test_dev.py
- tests/test_processors.py
> Don't crash in exception() if outside of an exception

- docs/api.rst
I noticed *json_kw* was referred to in docs but the the actual parameter is called *dumps_kw*. While fixing that I also wanted to add a little bit of info I had to figure out on my own, which was that if you want `orjson` to handle serialization of dataclasses, datetimes, etc. natively, you need to pass a `default` (I used the `singledispatch` to use `str` by default and handle Pydantic objects and sets to work better with our logging systems)
Do I need to add to the changelog? 🤔 
> Update JSONRenderer docs

- CHANGELOG.md
- src/structlog/_frames.py
- src/structlog/_log_levels.py
- src/structlog/contextvars.py
- src/structlog/processors.py
- src/structlog/stdlib.py
- tests/test_processors.py
Added support for proper callsite parameters while operating under `asyncio`
The next version is the second number in the current release + 1. The first number represents the current year. So if the current version on PyPI is 23.1.0, the next version is gonna be 23.2.0. If the next version is the first in the new year, it'll be 24.1.0.
> callsite parameter fix while operating under `asyncio`

- docs/configuration.md
Update the structlog configure call in the configuration documentation to use an instance of LoggerFactory instead of the class definition.
> docs: Update configuration documentation

- .github/workflows/ci.yml
Let's measure the vroom-vroom!
> Use tox-uv in CI

- src/structlog/_frames.py
Skip temporary tuple.
Performance impact is very small. But it makes code simpler.
> optimize `_find_first_app_frame_and_name`

- src/structlog/_output.py
- src/structlog/_utils.py
- src/structlog/twisted.py
- tests/test_utils.py
Retry is not needed since Python 3.5.
https://peps.python.org/pep-0475/
> remove `until_not_interrupted()`

- CHANGELOG.md
- src/structlog/stdlib.py
- tests/processors/test_processors.py
I believe this fixes #615 @IanTaylorFB – it was rather simple thanks to your MRE, thank you!
> stdlib: add callsite collection support for async methods

- README.md
for some reasons i don't see the logos :(
> docs: try adding empty lines

- .github/workflows/ci.yml
Let's see if it makes a (positive) difference.
> Use setup-cached-uv

- .gitignore
- CHANGELOG.md
- src/structlog/dev.py
- tests/test_dev.py
https://github.com/hynek/structlog/issues/647
> quote str value with special char in dev output

- docs/frameworks.md
The `hex` function does not format the trace and span id correctly.  In as much as the spec [says](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#retrieving-the-traceid-and-spanid) the span-id and trace-id are fixed with hex numbers. 16 chars for the span-id and 32 for the trace-id.
> Fix Open Telemetry framework example

- CHANGELOG.md
- src/structlog/_native.py
> Map native fatal to critical

- CHANGELOG.md
- src/structlog/dev.py
This PR simply adds `RichTracebackFormatter` to `__all__`.
Fixes https://github.com/hynek/structlog/issues/700
> expose RichTracebackFormatter for imports in structlog.dev

- CHANGELOG.md
- src/structlog/processors.py
This PR simply adds `LogfmtRenderer` to `__all__`.
> expose LogfmtRenderer for imports
