hynek/structlog

docs/api.rst, docs/changelog.rst, structlog/stdlib.py, tests/test_stdlib.py
=> Add stdlib.BoundLogger.log

docs/api.rst, docs/changelog.rst, structlog/stdlib.py, tests/test_stdlib.py
=> Add add_log_level() and add_logger_name() stdlib processors

AUTHORS.rst, structlog/stdlib.py, tests/test_stdlib.py
Using ``logger.exception(e)`` failed with processor ``structlog.stdlib.filter_by_level``
=> Add exception among supported levels in stdlib

docs/changelog.rst, structlog/processors.py, tests/test_processors.py
In my environment, the logging standard is to store the human-readable timestamp in a ``'time'`` entry :)
=> Add option to specify key in TimeStamper processor

README.rst
and move `.. begin` so example doesn't appear twice in sphinx docs
Preview `README.rst` at https://github.com/msabramo/structlog/blob/README_teaser/README.rst
=> README.rst: Include example

AUTHORS.rst, docs/changelog.rst, structlog/_frames.py, tests/test_frames.py
In my own code, I got a new traceback for this issue (meant to be fixed in release of 15.1.0)
With some DEBUG prints sprinkled in, I was able to see that ``f.f_frame.has_key("__name__")`` was ``True``, however ``f.f_frame.get("__name__", "?")`` would still return ``None`` thus skipping that default choice.
Per python docs, ``foo.get("whatever")`` already has a default value of ``None`` so simply mixing them with "or" will achieve the desired goal here in all existing cases, as well as fix my own case.
For reference the full traceback I had:
```
Traceback (most recent call last):
File "/data/www/relengapi/celery", line 81, in <module>
load_entry_point('celery', 'console_scripts', 'celery')()
File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/celery/__main__.py", line 30, in …
```
=> Better support for missing __name__ in frame traversal

src/structlog/_frames.py, tests/test_frames.py
I ran into this scenario running the tests for my app. It opens some connections to a cassandra cluster, runs some tests, and (sometimes) doesn't close the connection. Each cluster registers an `atexit` function which closes the connection. 
When `py.test` runs these tests, just before quitting it prints the following traceback:
```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
File "cassandra/cluster.py", line 2184, in cassandra.cluster.ControlConnection.shutdown (cassandra/cluster.c:39664)
File "/usr/lib/python3.4/logging/__init__.py", line 1267, in debug
self._log(DEBUG, msg, args, **kwargs)
File "/usr/lib/python3.4/logging/__init__.py", line 1404, in _log
fn, lno, func, sinfo = self.findCaller(stack_info)
File …
```
=> Protect from scenarios where all frames should be ignored

src/structlog/_config.py, tests/test_config.py
Fix #71 by not caching *any* part of the configuration in the proxy unless explicitly requested. This makes the `_logger` attribute consistent with other parameters of the BoundLoggerLazyProxy such as `_processors`, `_wrapper_class`, and `_context_class`.
=> Don't cache logger

src/structlog/processors.py, tests/test_processors.py
According to the documentation [https://docs.python.org/2/library/logging.html#logging.Logger.debug] the exc_info argument should support not only boolean values, but also values evaluating to True.
This fix should solve the case when someone is using:
`log.debug('Debug message', exc_info=1)`
=> Handling the case when exc_info is not True but evalues to True

docs/faq.rst
We should be using `record.getMessage()` instead of `record.msg` to ensure that third party libraries logs are formatted.
=> [Doc] Handle log formatting for third party components

CHANGELOG.rst, src/structlog/stdlib.py
stdlib error log records were sometimes logged with exception level, sometimes
logged with error level by structlog. This is due to the non 1-1 mapping
between log levels and log names (some levels have the same name). If the
developer adds a new log name that conflicts with an already existing log
level without blacklisting it, it produces the unexpected behavior. It's even
random in Python 3: because of the hash seed, it will always produce the same
result in the same python interpreter instance, but will vary according to the
interpreter instance.
The problem is that once the mistake is done, it's pretty complicated to debug.
And it's even more complicated to write a test (since you will never notice a
behavior change in the same python instance). I think it would be a good idea
to add …
=> Fix stdlib errors being logged as exceptions sometimes.

CHANGELOG.rst, docs/api.rst, docs/standard-library.rst, src/structlog/stdlib.py, tests/test_base.py, tests/test_stdlib.py
First off, I’m terribly sorry I didn’t get around it any sooner.  However given how long it took me to dive back into `logging`, I guess my procrastination was warranted. :(
Anyhow, @insolite, and @if-fi I’d like your feedback on what I’ve molded based on your PR and comments.  Does this solve your problem?  I’ve tried to make it more useful by adding the possibility to run stdlib entries through a separate chain, does that make sense to you?
I hope we’ll be able to close these PRs/issues soon.
Again: sorry.
=> Add ProcessorFormatter

CHANGELOG.rst, src/structlog/stdlib.py, tests/test_stdlib.py
This fixes #116 and *probably* http://stackoverflow.com/questions/43855507/configuring-and-using-structlog-with-django .
@if-fi did I miss something obvious that will break everything for everyone? also cc @gilbsgilbs who seems to know a lot more about stdlib logging than I. :)
=> Clear args on LogRecords after rendering them in ProcessorFormatter

CHANGELOG.rst, src/structlog/stdlib.py, tests/test_stdlib.py
Based on / fixes #109 
Hey @andreiko I tried to push it to your branch but I failed at git hard (due to the changes in master) so here’s a new pull request with some changes (and split up of stack_info & exc_info handling).
Does this still fix your problem and do you agree with the approach?
=> Fix exc_info and race condition in ProcessorFormatter

docs/thread-local.rst
Threadlocal docs currently say to use an _instance_ of `WrappedDictClass` as the `context_class`, i.e.:
```
configure(context_class=WrappedDictClass())
```
The call above doesn't actually set `context_class` at all, b/c an empty `WrappedDictClass` instance evaluates to falsey and so fails the `if context_class` check in [`configure()`](https://github.com/hynek/structlog/blob/master/src/structlog/_config.py#L164). If we manage to actually set `context_class` as an _instance_ rather than a _class_, attempts to `.bind()` result in error: 
```
TypeError: 'WrappedDict-f8fcd814-393b-4ddf-b539-c55e7bd04e62' object is not callable
```
Worth noting that the [threadlocal tests](https://github.com/maiamcc/structlog/blob/master/tests/test_threadlocal.py#L37) all test behavior with a `wrap_dict` …
=> [DOCS] fix threadlocal docs to provide correct example

.travis.yml, CHANGELOG.rst, src/structlog/twisted.py, tox.ini
If a failure is already a Failure instance, don't encapsulate it into
a Failure. Keep it as is.
Fix #144 
Note that I have no clue if this is actually correct. This fixes the failing test and it doesn't seem dumb to do that. I didn't investigate what changes triggered this problem. Maybe `Failure` was not a `BaseException` in the past.
=> twisted: don't encapsulate failures twice

CHANGELOG.rst, src/structlog/dev.py, tests/test_dev.py, tests/test_twisted.py
Add option to ConsoleRenderer for sending colored logs to non-tty destinations. 
The main use case is that of files meant to be streamed to the console. 
We use this with docker logs.
Also included is a fix for a unit test.
=> Send colored logs to non-tty destinations + fix for a unit test

CHANGELOG.rst, docs/api.rst, docs/standard-library.rst, src/structlog/stdlib.py, tests/test_loggers.py, tests/test_stdlib.py, tests/test_twisted.py
When combing through logs, I find it's sometimes helpful to filter by a range of log levels. Currently this must be done by checking log level strings. This adds the number so it's easier to do such a check:
With only log levels:
`log_level in ("error", "warning", "critical")`
With log level numbers:
`log_level_number >= 30`
=> Add log level numbers

src/structlog/_frames.py
```
Exception ignored in: <generator object _find_first_app_frame_and_name.<locals>.<genexpr> at 0x10693ad00>
Traceback (most recent call last):
File "/Users/ricardopinto/a_project/env/lib/python3.6/site-packages/structlog/_frames.py", line 42, in <genexpr>
while any(name.startswith(i) for i in ignores):
SystemError: error return without exception set
```
From what I saw, `ignores` was `['structlog', 'logging']`, and `name` was `structlog._frames`.
Python version is 3.6.5, structlog is 18.1.0.
=> Added brackets to list comprehension, fixing this exception:

src/structlog/stdlib.py, tests/test_stdlib.py
=> Pass-through stdlib's logger attributes

.travis.yml, src/structlog/stdlib.py, tox.ini
Tests fail on Python 3.8:
```
structlog/stdlib.py:75: in warning
return self._proxy_to_logger("warning", event, *args, **kw)
structlog/stdlib.py:118: in _proxy_to_logger
return super(BoundLogger, self)._proxy_to_logger(
structlog/_base.py:192: in _proxy_to_logger
return getattr(self._logger, method_name)(*args, **kw)
/usr/lib64/python3.8/logging/__init__.py:1457: in warning
self._log(WARNING, msg, args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <_FixedFindCallerLogger tests.test_stdlib (DEBUG)>, level = 30
msg = {'event': 'foo', 'level': 'warning'}, args = (), exc_info = None
extra = {'_logger': <_FixedFindCallerLogger tests.test_stdlib (DEBUG)>, '_name': 'warning'}
stack_info = False, stacklevel = 1
def _log(self, level, msg, args, …
```
=> Python 3.8 support

docs/configuration.rst
I developped a pypi package to easily integrate structlog in django (it also includes a celery integration). I thought it would be helpful to add a reference to it in your documentation.
doc: https://django-structlog.readthedocs.io/en/latest/?badge=latest
pypi: https://pypi.org/project/django-structlog/
github: https://github.com/jrobichaud/django-structlog/
=> Add reference to django-structlog

docs/getting-started.rst
Little typing error fix in `getting-started.rst`: fa~s~cilitate.
=> Fix typo in getting-started.rst

docs/getting-started.rst, src/structlog/_config.py
This facilitates making small and informed changes to the default processor list before delving into deeper docs or code. Mentioned at the end of #173, though it is not addressed to that bug.
=> Show the default processor list configuration in getting-started

CHANGELOG.rst, src/structlog/stdlib.py, tests/test_stdlib.py
`filter_by_level` processor needs logger object in order to find out what is the log level. Add `logger` as an argument to `ProcessorFormatter` and then pass it through the processor chain so `filter_by_level` can use it.
Related to #195
=> Add logger argument to ProcessorFormatter

src/structlog/dev.py, tests/test_dev.py
`colorama` isn't a direct dependency of `structlog`, and as such it might not be available. The console renderer should still work when it isn't, though.
=> ConsoleRenderer: default to colorless when colorama is unavailable

CHANGELOG.rst, docs/api.rst, docs/thread-local.rst, src/structlog/threadlocal.py, tests/test_threadlocal.py
Fixes #222 
caveat: I didn't duplicate the greenlet support because it turns out greenlet.getcurrent() doesn't seem to return separate objects for different OS-level Python threads. That means that if you somehow have `greenlet` in your dependency tree, the existing thread-local stuff will just straight up not work.
If someone cares I'm sure it'd be possible to implement something that uses greenlets and threadlocal in a way that ensures that you get distinct values in different greenlets AND distinct values in different python threads.
=> A newer, better thread-local API

src/structlog/stdlib.py, tests/test_stdlib.py
Resolves #227 
When migrating a project from stdlib logging to `structlog`, an easy first step is to use `ProcessorFormatter` with processors defined in `foreign_pre_chain`. These will run on every stdlib log message sent into the formatter.
However, right now there is no way to access a LogRecord's `args` in the `foreign_pre_chain` processors because they are stripped before the record is passed to the processors.
This PR introduces a `pass_foreign_args` kwarg to `ProcessorFormatter`. When set to `True`, it will inject a foreign log record's `args` attribute into the `event_dict` under the `positional_args` key before stripping them from the record.
=> Allow foreign_pre_chain To Read Foreign Log Args

CHANGELOG.rst, docs/api.rst, docs/contextvars.rst, docs/thread-local.rst, src/structlog/_base.py, src/structlog/contextvars.py, src/structlog/threadlocal.py, tests/test_contextvars.py, tests/test_threadlocal.py
=> Harmonize names

CHANGELOG.rst, src/structlog/dev.py
Fixes #232 
Could you check if this helps @wimglenn?
I've decided to go the grossest possible route: non-lazy on Windows, lazy everywhere else…
cc @MarkusH
=> Don't be lazy on Windows

azure-pipelines.yml, setup.py
This hopefully fixes `pip install -e .` on Windows as mentioned in #242.
=> Make pip install -e . work on Windows

docs/standard-library.rst
=> docs/standard-library.rst: fix typo

docs/thread-local.rst
=> Fix a tiny typo s/threadn-locals/thread-locals

CHANGELOG.rst, docs/standard-library.rst, docs/twisted.rst, src/structlog/_config.py, src/structlog/threadlocal.py, tests/test_config.py, tests/test_loggers.py
Hi!
I was browsing the source code and noticed some typo in "iff" word (macbook keyboard?) 
But then I decided to go further and try out this nice [tool](https://github.com/vlajos/misspell-fixer), so found a bit more 🙂
There's also a [Github Action](https://github.com/sobolevn/misspell-fixer-action) for it if you think it's useful.
Thanks for the awesome library!
_contribution checklist is omitted, cause this is just about typos_
=> Fix several typos

docs/testing.rst, src/structlog/testing.py
We got confused at work when `structlog.testing.capture_logs` did not seem to capture `contextvars` bindings. Looking at the implementation made it clear, but it would be nice to document it. Which is what I'm doing here!
Thanks for structlog!
=> Document that capture_logs disables configured processors

docs/contextvars.rst
=> Fix spelling in contextvars docs

docs/processors.rst
Added just the doc clarification from #263. I think it's useful even if we don't want to add the clarification at runtime.
=> Add docs clarification for processors example

CHANGELOG.rst, src/structlog/stdlib.py, tests/test_stdlib.py
I encountered this issue when combining structlog, stdlib logging, and structlog-sentry. structlog-sentry always attaches the current stack trace to events: https://github.com/kiwicom/structlog-sentry/blob/c15fdb076900e87e577bd0f2d7ef0d847706b366/structlog_sentry/__init__.py#L45 . Unfortunately because `ProcessorFormatter.format` was using an `AttributeError` for control flow, that would mean the current exception fetched by `sys.exc_info()` would always be that `AttributeError`.
This PR adds a test for that case, and changes `ProcessorFormatter.format` to use `hasattr` to check for wrapped event dicts.
This is just a friendly reminder about the most common mistakes.  Please make sure that you tick all boxes.  But please read our [contribution …
=> Remove exception control flow from ProcessorFormatter

docs/performance.rst, docs/testing.rst
=> Document that capture_logs() relies on un-cached loggers

docs/getting-started.rst, docs/loggers.rst, tests/test_config.py, tests/test_stdlib.py, tests/test_threadlocal.py, tests/test_twisted.py
When removing support for 2.7/3.5, most instances of OrderedDict were removed: this finishes the work. As a user, I was particularly confused by the mentions of OrderedDict in the docs for Python <3.6.
=> Stop using OrderedDict altogether

CHANGELOG.rst, docs/api.rst, docs/getting-started.rst, docs/loggers.rst, docs/logging-best-practices.rst, docs/performance.rst, docs/processors.rst, docs/testing.rst, docs/thread-local.rst, src/structlog/__init__.py, src/structlog/_config.py, src/structlog/_log_levels.py, src/structlog/processors.py, src/structlog/testing.py, src/structlog/types.py, tests/test_config.py, tests/test_log_levels.py, tests/test_processors.py, tests/test_testing.py
Remove LevelFilter, this is much faster.
Since we needed a better way for testing, I've also added CapturingLogger.
=> Implement native log levels though an optimized bound logger

.pre-commit-config.yaml, CHANGELOG.rst, conftest.py, docs/api.rst, docs/conf.py, docs/standard-library.rst, setup.py, src/structlog/stdlib.py, tests/test_loggers.py, tests/test_stdlib.py, tests/test_twisted.py
This is so far only an experimental WiP/PoC. But unless I'm missing anything, adding truly async loggers shouldn't be much of a problem.
---
You can use it like this:
```python
import structlog
import asyncio
import logging
import sys
logging.basicConfig(
format="%(message)s",
stream=sys.stdout,
level=logging.INFO,
)
structlog.configure(
processors=[
structlog.stdlib.filter_by_level,
structlog.stdlib.add_logger_name,
structlog.stdlib.add_log_level,
structlog.stdlib.PositionalArgumentsFormatter(),
structlog.processors.TimeStamper(fmt="iso"),
structlog.processors.StackInfoRenderer(),
structlog.processors.format_exc_info,
structlog.processors.UnicodeDecoder(),
structlog.processors.JSONRenderer()
],
context_class=dict,
logger_factory=structlog.stdlib.LoggerFactory(), …
```
=> Implement async bound loggers for stdlib

src/structlog/contextvars.py
With the current type, using it in a processor chain requires a
cast to `types.Processor`; replace use of `types.Context` with
`types.EventDict` to fix that.
=> Fix type of contextvars.merge_contextvars

CHANGELOG.rst, docs/contextvars.rst, src/structlog/contextvars.py, src/structlog/stdlib.py, tests/test_contextvars.py
=> Fix context vars

src/structlog/processors.py
=> Add missing backtick to ExceptionPrettyPrinter docstring

docs/performance.rst, docs/thread-local.rst, setup.py, src/structlog/dev.py, src/structlog/stdlib.py, tests/test_config.py, tests/test_stdlib.py, tests/test_testing.py
There are small typos in:
- docs/performance.rst
- docs/thread-local.rst
- src/structlog/dev.py
- src/structlog/stdlib.py
- tests/test_config.py
- tests/test_stdlib.py
- tests/test_testing.py
Fixes:
- Should read `passed` rather than `passsed`.
- Should read `length` rather than `lenght`.
- Should read `initial` rather than `initia`.
- Should read `flexibility` rather than `flexibiliy`.
- Should read `contextmanager` rather than `contextmanger`.
- Should read `appropriate` rather than `apropriate`.
- Should read `recommend` rather than `recomment`.
Closes #319
This is just a friendly reminder about the most common mistakes.  Please make sure that you tick all boxes.  But please read our [contribution guide](https://www.structlog.org/en/latest/contributing.html) at least once, it will save …
=> docs: fix a few simple typos

docs/performance.rst
Updated the sample code to include `TimeStamper(utc=True)` instead of `False`.
=> Fix typo in performance.rst

CHANGELOG.rst, docs/development.rst, docs/getting-started.rst, src/structlog/_config.py, src/structlog/dev.py, tests/test_dev.py
This PR was inspired by the frustration and confusion I suffered over the last week, dealing with figuring out why colored logging wan't working on my apps, despite everything seemingly having been configured properly. I eventually tracked it down to the `self.stream.isatty()` check on `colorama`'s `ansitowin32.py` file, line 92. Because my apps run in Docker containers, they don't log directly to a TTY, so it was returning False and forcing the ANSI-to-Win32 color code conversion, even though my apps run on Linux. This broke all the colors.
Yes, fixing this is what `ConsoleRenderer`'s `force_colors` kwarg appears to be for, but I was using an old version of `ConsoleRenderer` from before that was added, and didn't realize it.
Ultimately, though, my experience showed me that `colorama` …
=> Cease all use of Colorama on non-Windows systems.

CHANGELOG.rst, docs/api.rst, docs/conf.py, docs/contextvars.rst, src/structlog/contextvars.py, tests/test_contextvars.py
Update `structlog.contextvars.bind_contextvars()` to return a `Mapping[str, contextvar.Token]` corresponding to the results
of setting the requested contextvars.
This return value is suitable for use with the newly-added `structlog.contextvars.reset_contextvars()` function, which resets the requested contextvars to their previous values using the given Tokens.
If you have *any* questions to *any* of the points …
=> Add reset_contextvars and update bind_contextvars

CHANGELOG.rst, src/structlog/dev.py, tests/test_dev.py
=> Allow to preserve keys order in ConsoleRenderer. Related to #166

CHANGELOG.rst, src/structlog/processors.py, tests/test_processors.py
Because the reference to either `datetime.now()` or `datetime.utcnow()` is retrieved during `TimeStamper` is being created, it gets into trouble when FreezeGun or any similar mechanism that patches `datetime` module is applied before the instantiation.  This patchs proposes a modification to it so that the invocation to the "now" function will always be done with dereferences from the datetime module object, albeit the slight possible performance penalty.
=> Get TimeStamper working properly if datetime module is mocked before its instantiation

CHANGELOG.rst, src/structlog/__init__.py
Not sure how a specific test can be launched with this env variable (PYTHONOPTIMIZE=2)
=> fix __doc__ is None in optimized mode

CHANGELOG.rst, docs/api.rst, pyproject.toml, src/structlog/processors.py, tests/test_processors.py, tests/typing_examples.py
This PR adds a `LogfmtRenderer` processor to format log lines in the [logfmt](https://brandur.org/logfmt) format.
The core of the work is done by the [`logfmt`](https://pypi.org/project/logfmt/) library, which is added as global dependency. Or should this be changed to feature-based optional?
Refactored the code in `KeyValueRenderer` to share the `sort_keys`/`key_order`/`drop_missing` logic. Tests are directly adapted from `KeyValueRenderer`.
Closes #322 
This is just a friendly reminder about the most common mistakes.  Please make sure that you tick all boxes.  But please read our [contribution guide](https://github.com/hynek/structlog/blob/main/.github/CONTRIBUTING.md) at least once, it will save you unnecessary review cycles!
If an item doesn't apply to your pull request, **check it …
=> Add LogfmtRenderer

src/structlog/dev.py, src/structlog/stdlib.py
Fixed spelling mistakes in comment
Picked it up running:
```bash
pylint \
--disable all \
--enable spelling \
--spelling-dict en_US \
--spelling-private-dict-file=~/.config/pylint-dict \
src/structlog/stdlib.py
```
This is just a friendly reminder about the most common mistakes.
Please make sure that you tick all boxes.
But please read our [contribution guide](https://github.com/hynek/structlog/blob/main/.github/CONTRIBUTING.md) at least once; it will save you unnecessary review cycles!
If you …
=> Fix spelling mistakes in comments

src/structlog/stdlib.py
The comment explains the copying of the `allow` parameter's content to a new list.
This is just a friendly reminder about the most common mistakes.
Please make sure that you tick all boxes.
But please read our [contribution guide](https://github.com/hynek/structlog/blob/main/.github/CONTRIBUTING.md) at least once; it will save you unnecessary review cycles!
If you have *any* questions to *any* of the points above, just **submit and ask**!
This checklist is here to *help* you, not to deter you …
=> Add an explaining comment to ExtraAdder

CHANGELOG.rst, docs/api.rst, docs/standard-library.rst, src/structlog/_utils.py, src/structlog/processors.py, tests/test_processors.py, tests/test_utils.py, tests/utils.py, typing_examples.py
This PR creates a `CallsiteParameterAdder` processor which will populate the event dictionary with callsite parameters.
The following callsite parameters are supported:
```
FILENAME = 'filename'
The basename part of the full path to the python source file of the callsite.
FUNC_NAME = 'func_name'
The name of the function that the callsite was in.
LINENO = 'lineno'
The line number of the callsite.
MODULE = 'module'
The python module the callsite was in. This mimicks the module attribute of logging.LogRecord objects and will be the basename, without extension, of the full path to the python source file of the callsite.
PATHNAME = 'pathname'
The full path to the python source file of the callsite.
PROCESS = 'process'
The ID of the process the callsite was executed in.
PROCESS_NAME = …
```
=> Add CallsiteParameterAdder processor

CHANGELOG.rst, src/structlog/types.py, typing_examples.py
This narrows the return type of `bind`,`unbind`,`try_unbind` and `new`
in `FilteringBoundLogger` to return `FilteringBoundLogger` instead of
`BindableLogger`. This makes it easier to use structlog in a typed
context like this:
```python
def typecheck_filtering_return() -> None:
fblogger: FilteringBoundLogger = structlog.get_logger(__name__)
fblog = fblogger.bind(key1="value1", key2="value2", key3="value3")
fblog.info("values bound")
fblog = fblog.unbind("key1")
fblog.debug("value unbound")
fblog = fblog.try_unbind("bad_key")
fblog.warn("no value unbound because key not defined")
fblog = fblog.new(new="value")
fblog.info("this is a whole new logger")
```
Without this change the above example will result in a type
error when using `mypy --strict` as the type of `fblog` will be …
=> Narrow the return type of bind,unbind,try_unbind,new in subclass

src/structlog/_loggers.py, tests/test_loggers.py
=> PrintLogger: switch to print

CHANGELOG.rst, src/structlog/_log_levels.py, tests/test_log_levels.py
In my team's app, we're using `make_filtering_bound_logger` in our configuration, which is working fine except in one corner case. Another developer introduced a bug that was missed in review and testing, and it only appears at runtime when the log level is DEBUG (below INFO, our standard level):
```py
log.debug(x=y)
```
Obviously this is incorrect: there needs to be an `event` string in this call. However, the original `_nop` method that gets returned has no checks for this missing argument, so their (admittedly poor) testing didn't turn up a problem at this line. Later when running at DEBUG level to research a different issue, the entire app failed to start up because of this call alone.
Root cause for us was incorrect code from our teammate, but I figured it could use some help from …
=> fix: Use a noop with the same signature as the real one for make_filtering_bound_logger

CHANGELOG.rst, src/structlog/_loggers.py, tests/test_loggers.py
The WriteLogger.
Let me know if this is good and I can add some docs.
=> Implement WriteLogger

src/structlog/_config.py
In some Python environments (e.g. Maya 2022's mayapy.exe), sys.stdout has been monkey-patched to something other than the expected stdout. As such, it doesn't actually have an `isatty` method and raises an AttributeError in response.
=> Handle monkey-patched stdout

CHANGELOG.md, src/structlog/testing.py, tests/test_testing.py
This changes the `structlog.testing.capture_logs` contextmanager to also work for already initialized bound loggers.
Fixes #408.
=> Apply capture_logs to initialized bound loggers

docs/standard-library.rst
Fixes configuration sample in "Standard Library Logging" documentation page. At least as of 21.5.0 copy-pasting it required changes for it to work,
=> Fix configuration example for stdlib

CHANGELOG.md, src/structlog/_log_levels.py, tests/test_log_levels.py
add `log()` to `BoundLoggerFiltering*` to better match `BoundLogger` signature 
- [?] **New APIs** are added to [`typing_examples.py`](https://github.com/hynek/structlog/blob/main/tests/typing_examples.py) (not actually new, just fixes `stdlib.get_logger().log()`)
=> add log() to BoundLoggerFiltering*

.github/workflows/main.yml, tests/test_processors.py, tests/test_threadlocal.py, tox.ini
Looks like only the more helpful exceptions are tripping us up.
=> Add support for 3.11-beta

CHANGELOG.md, docs/api.rst, docs/getting-started.rst, docs/standard-library.rst, src/structlog/_config.py, src/structlog/stdlib.py, tests/test_stdlib.py
@pradyunsg you asked for this, you're reviewing it. ;)
=> Add structlog.stdlib.recreate_defaults

docs/logging-best-practices.rst
The [Thread Locals doc](https://www.structlog.org/en/22.1.0/thread-local.html) is now legacy and deprecated, so the [Logging Best Practices doc](https://www.structlog.org/en/stable/logging-best-practices.html) should link to the the now recommended [Context Variables](https://www.structlog.org/en/stable/contextvars.html) document directly and use different wording when doing so, as it's not just thread context any more.
These are mostly not applicable to this one-line documentation fix
=> Avoid deprecated thread locals from best practices

.github/workflows/ci.yml, CHANGELOG.md, docs/getting-started.md, docs/why.rst, readthedocs.yml, src/structlog/_log_levels.py, src/structlog/types.py, tests/test_log_levels.py, tox.ini, typing_examples.py
This adds string interpolation to FilteringBoundLogger for users who want more human-friendly log messages and improves stdlib drop-in compat:
```pycon
>>> log.info("Hello %s! The answer is %d.", "World", 42, x=1)
2022-10-07 10:04.31 [info     ] Hello World! The answer is 42. x=1
```
Hopefully fixes #439
=> Add string interpolation to FilteringBoundLogger

.pre-commit-config.yaml, CHANGELOG.md, docs/getting-started.md, src/structlog/_log_levels.py, src/structlog/typing.py, tests/test_log_levels.py
This is asyncio support for non-stdlib, trying out a different approach that in hindsight makes more sense: add explicitly async functions in addition to the normal ones.
=> Add async log methods to filtering bound logger

docs/recipes.md
Recipe for passing context to worker threads as described over at https://github.com/hynek/structlog/issues/425.
=> recipe for passing context to worker threads

src/structlog/typing.py, typing_examples.py
=> Adds `log()` and `alog()` to `FilteringBoundLogger`.

src/structlog/testing.py
=> Updates __all__ to include all names in testing module API docs.

CHANGELOG.md, src/structlog/_log_levels.py, tests/test_log_levels.py
=> Fix interpolation in filtered log calls

CHANGELOG.md, src/structlog/_log_levels.py, tests/test_log_levels.py
This is how I've solved #488 for my needs.
I've not updated the test cases. I can do it, if you're happy with this change.
=> Fix missing exception info in aexception()

CHANGELOG.md, docs/api.rst, docs/getting-started.md, docs/standard-library.md, pyproject.toml, src/structlog/stdlib.py, tests/test_log_levels.py, tests/test_stdlib.py, tox.ini, typing_examples.py
This seems the better approach than AsyncBoundLogger.
=> Add async log variants to structlog.stdlib.BoundLogger

CHANGELOG.md, docs/console-output.md, src/structlog/_config.py, tox.ini
=> Add support for NO_COLOR

src/structlog/_log_levels.py, tests/test_log_levels.py
Possible solution for https://github.com/hynek/structlog/issues/530
=> Allow positional args in `exception`

CHANGELOG.md, docs/api.rst, docs/conf.py, src/structlog/dev.py, tests/test_dev.py
Sadly, it has to be class to be pickleable.
Fixes #490
=> Add structlog.dev.RichTracebackFormatter

docs/standard-library.md
This is very minor, but if you copy/paste the configuration example from the docs ([Standard Library Logging](https://www.structlog.org/en/stable/standard-library.html#rendering-using-structlog-based-formatters-within-logging)) into your app, you'll get something with 3-space indents which [black](https://github.com/psf/black) wants to change.
=> blacken stdlib example from docs

docs/getting-started.md
=> Fix "default" TimeStamper args in docs/getting-started.md

docs/configuration.md, docs/recipes.md, docs/standard-library.md
The next version is the second number in the current release + 1. The first number represents the current year. So if the current version on PyPI is 23.1.0, the next version is gonna be 23.2.0. If the next version is the first in the new year, it'll be 24.1.0.
=> Minor typo fixes

CHANGELOG.md, src/structlog/_config.py, src/structlog/threadlocal.py, tests/test_config.py
=> Make instances of BoundLoggerLazyProxy BindableLoggers on Python 3.12

CHANGELOG.md, tests/test_contextvars.py
While I was mucking with code, came across a coming depreciate from `pytest-asyncio` where they are deprecating using the `event_loop` fixture in favor of the more portable:
```python
event_loop = asyncio.get_running_loop()
```
Migrated to this [recommended](https://github.com/pytest-dev/pytest-asyncio/issues/638) method.
There's a ton of footguns waiting if you don't heed this warning. You can still go back to your project, create a branch from your main branch, push it, and open the pull request from the new branch.
This is not a pre-requisite for your your pull request to be accepted, but **you have been warned**.
The next version is the second number in the current release + 1. The first number represents the current year. So if the current …
=> Migrated from `event_loop` fixture

CHANGELOG.md, src/structlog/stdlib.py, src/structlog/typing.py, tests/test_stdlib.py
Closes #571 
It does these things:
- Makes the `structlog.stdlib.BoundLogger.exception` proxy to the wrapper `Logger`'s `exception` method, instead of `error`. This is useful for the niche use case of `Handler` classes that need to deal with both structlog and non-structlog records and prevents such handlers having to reconstruct `record.exc_info` for themselves or rely on structlog processors to do it
- Makes the handling of `ProcessorFormatter`'s `keep_exc_info` and `keep_stack_info` args consistent for log records originating from both structlog and non-structlog loggers.
- This is not a …
=> Make stdlib.BoundLogger.exception call Logger.exception

CHANGELOG.md, src/structlog/dev.py
The `width` argument of `RichTracebackFormatter` currently has no effect. This can be fixed by explicitly setting the `width` of the `Console` that is used to render the traceback.
=> don't ignore the width parameter in RichTracebackFormatter

CHANGELOG.md, src/structlog/_log_levels.py, tests/test_stdlib.py
Changes the displayed log level added by the `add_log_level` processor for logs using the `exception()` method to `"error"` instead of `"exception"`. This replicates the behaviour of CPython and structlog pre-23.3.0 (#572).
This issue has been discussed in #584.
- The next version is the second number in the current release + 1. The first number represents the current year. So if the current version on PyPI is 23.1.0, the next version is gonna …
=> Display "exception" logs as level "error"

CHANGELOG.md, src/structlog/processors.py, tests/test_processors.py
Currently, the LogfmtRenderer doesn't escape newlines, so any newline in a field (most commonly exceptions, but also other fields) ends up breaking the log over multiple lines, which messes up with log processing downstream.
This PR makes it so that newlines get escaped. I've checked that the behaviour is identical to the implementations in https://github.com/jteppinette/python-logfmter/ and https://github.com/sirupsen/logrus (which are the other logfmt implementations I happen to be using).
- This is not a pre-requisite for your your pull request to be accepted, but **you have been …
=> Escape newlines in LogfmtRenderer

src/structlog/dev.py
Fix broken rendering in API document.
https://www.structlog.org/en/stable/api.html#structlog.dev.ConsoleRenderer
=> fix doc rendering

CHANGELOG.md, src/structlog/processors.py, tests/processors/test_renderers.py
Fixes #511, closes #513
@davellas and @madjar – how does this look?
=> Fix Logfmt escaping

CHANGELOG.md, src/structlog/processors.py, tests/processors/test_processors.py
Prior to this commit, the `CallsiteParameterAdder` object could not be pickled.  As a result, structlog configurations could not be propagated to subprocesses using `pickle.dumps(structlog.get_config())`.  This commit updates the handlers in `CallsiteParameterAdder._handlers` to be free functions, rather than lambda functions, so that all class members can be pickled.
Closes #600
- [n/a] **New APIs** are added to our typing tests in …
=> Allow CallsiteParameterAdder to be pickled

CHANGELOG.md, src/structlog/processors.py
CallsiteParameterAdder is slower than logging.Logger.findCaller() because findCaller() doesn't use inspect at all.
~This commit doesn't stop using inspect.getframeinfo(), but skips heavy code_context calculation.~
This commit changes CallsiteParameterAdder to use frame object directly like findCaller().
**Bench:**
```py
import structlog
import timeit
import os
null = open(os.devnull, "w", encoding="utf-8")
structlog.configure(
processors=[
structlog.processors.CallsiteParameterAdder([
structlog.processors.CallsiteParameter.FILENAME,
structlog.processors.CallsiteParameter.LINENO,
]),
structlog.processors.JSONRenderer()
],
logger_factory=structlog.PrintLoggerFactory(null),
cache_logger_on_first_use=False
)
log = structlog.get_logger()
N = 100_000
x = timeit.timeit(lambda: log.info("hello"), …
```
=> optimize CallsiteParameterAdder

docs/standard-library.md
I read [Standard Library](https://www.structlog.org/en/stable/standard-library.html) document and tested some configurations. I see "Don't Integrate" approach is faster than integrate approaches.
So I want to improve the "Don't Integrate" section a bit:
* Mention about ProcessorFormatter can be used for logging formatter. It is easier than python-json-logger when I want to use similar format between structlog and logging.
* Note that PrintLogger is not safe when both of structlog and logging shares same output file.
- This is not a pre-requisite for your your pull request to be accepted, …
=> add some note about logging configuration

docs/getting-started.md
Just changing the name of one variable in one docs example.
While following along with the "Getting Started" guide for the first time, I got sidetracked for several minutes by this `logger`.
None of the example snippets earlier in the file assigned to a variable named `logger` (but they frequently assigned the result of `structlog.get_logger()` to a variable named `log`).
I spent a bit poking around in the API reference to try and figure out which types define a `.bind()` method and whether they completely overlap with the types returned by `structlog.get_logger()`.  
Eventually I decided the specific variable name probably wasn't a super considered choice and I was overthinking things.
Maybe this change could save someone time in the future.
It'd be nice (maybe not super valuable, but …
=> Fix reference to undefined var `logger` in "Getting Started" example

CHANGELOG.md, src/structlog/_log_levels.py, src/structlog/testing.py, tests/test_testing.py
The fix of mapping exception to error log level doesn't work in capture_log during test
See https://github.com/hynek/structlog/issues/584#issuecomment-2150290095
=> Map method name in capture_logs as well

CHANGELOG.md, docs/api.rst, docs/conf.py, src/structlog/tracebacks.py, tests/test_tracebacks.py
Restore feature parity between Rich's traceback extractor:
- When displaying locals, call `repr()` on strings, too.
- Add `locals_max_length` config option
- Add `locals_hide_sunder` config option
- Add `locals_hide_dunder` config option
- Add `suppress` config option
- The next version is the second number in the current release + 1. The first number represents the current year. So if the current version on PyPI is 23.1.0, the next version is …
=> Improve dict traceback

.readthedocs.yaml, docs/conf.py, docs/index.md, pyproject.toml
Currently the main page isn't updated on build which means the sponsor links are gonna go stale
=> Improve RTD and run Cog on docs build

src/structlog/_log_levels.py
This doesn't actually need to be a `logging.Logger`, right?
=> Tweak `add_log_level` type

CHANGELOG.md, pyproject.toml, src/structlog/threadlocal.py, src/structlog/typing.py
As a nice demonstration of its purpose, it removes one `type: ignore` from our own code base.
Fixes #641
=> Make BindableLogger return Self on binds

src/structlog/_base.py, src/structlog/stdlib.py, src/structlog/typing.py, tests/typing/api.py
This Pull Request switches several `BoundLoggerBase` methods to annotate a return type of `typing_extensions.Self` instead of `BoundLoggerBase`. This change is consistent with the code which [returns specifically](https://github.com/hynek/structlog/blob/main/src/structlog/_base.py#L70) `self.__class__()` and with the tests that ensure the [type is preserved when `.bind()` is called](https://github.com/hynek/structlog/blob/main/tests/test_base.py#L82).
This should not have any runtime changes, but instead fixes a typing bug which caused the following code to incorrectly fail type-checking:
```python
from structlog import get_logger, BoundLogger
log: BoundLogger = get_logger()
log.info("This is OK")
log = log.bind() #  error: Type "BoundLoggerBase" is not assignable to declared type …
```
=> Switch base methods to return Self instead of BoundLoggerBase

src/structlog/_frames.py, src/structlog/tracebacks.py, tests/test_tracebacks.py
- Added a new utility function is_missing_exc_info to check if exc_info is missing.
- Updated ExceptionDictTransformer to return an empty list when exc_info is missing.
- Modified _format_exception to use the new is_missing_exc_info function.
- Added a test case to verify that ExceptionDictTransformer returns an empty list when exc_info is missing.
https://github.com/hynek/structlog/issues/656
- The next version is the second number in the current …
=> handle missing exc_info in ExceptionDictTransformer

CHANGELOG.md, src/structlog/dev.py, tests/test_dev.py
=> Stop mutating styles in ConsoleRenderer

src/structlog/stdlib.py, tests/test_stdlib.py
For better DX in IDEs.
Fixes #648
like this @trim21 or is something missing?
=> Use real methods for fatal/warn

docs/why.md
Fix a one-character typo in why.md.
The rest of the checklist is irrelevant for this change.
=> Fix a small typo.

CHANGELOG.md, src/structlog/_native.py, src/structlog/typing.py, tests/test_native.py, tests/typing/api.py
=> native loggers: add is_enabled_for & get_effective_level

CHANGELOG.md, src/structlog/processors.py, tests/processors/test_renderers.py
The default output doesn't change but manual formatting allows for TZ data now.
Fixes #703
cc @andrei-korshikov
=> TimeStamper() now uses TZ-aware objects

CHANGELOG.md, src/structlog/processors.py, tests/processors/test_processors.py
`structlog.processors.ExceptionPrettyPrinter` accepts an *exception_formatter* argument just like `structlog.processors.ExceptionRenderer` does, but it now actually uses the passed function instead of the default.
- The next version is the second number in the current release + 1. The first number represents the current year. So if the current version on PyPI is 23.1.0, the next version is gonna be 23.2.0. If the next version is the first in the new …
=> fix ExceptionPrettyPrinter custom formatter support

CHANGELOG.md, docs/api.rst, src/structlog/tracebacks.py, tests/test_tracebacks.py
=> tracebacks: Handle ExceptionGroup
